export default function capital() {
  return [
    {
      chargeId: 1000,
      chargeName: '本金',
      direction: 'RECEIVE',
      chargeCalcChannel: 'BILLING_SYSTEM',
      calcFormula: 'PRINCIPAL_YEAR_RATE',
      receiverName: null,
      receiverCode: null,
      receiverAgentCode: null,
      receiverAgentName: null,
      repayMethod: 'ONETIME_PRINCIPAL_INTEREST',
      termRule: 'HEAD_AND_TAIL',
      free: 'NO',
      unearned: 'NO',
      chargeMethod: 'ONE_TIME_CHARGE_BEFORE',
      fallbackRule: 'ALL_INTEREST',
      fallbackUpperLimitValue: null,
      fallbackUpperLowerValue: null,
      repayRule: 'REPAY_BOTH',
      settleByPrinciple: null,
      ratioModel: 'FIXED_RATIO',
      skuConfigVos: []
    },
    {
      chargeId: 1006,
      chargeName: '利息',
      direction: 'RECEIVE',
      chargeCalcChannel: 'BILLING_SYSTEM',
      calcFormula: 'PRINCIPAL_YEAR_RATE',
      receiverName: null,
      receiverCode: null,
      receiverAgentCode: null,
      receiverAgentName: null,
      repayMethod: 'ONETIME_PRINCIPAL_INTEREST',
      termRule: 'HEAD_NO_TAIL',
      free: 'NO',
      unearned: 'NO',
      chargeMethod: 'ONE_TIME_CHARGE_BEFORE',
      fallbackRule: 'ALL_INTEREST',
      fallbackUpperLimitValue: null,
      fallbackUpperLowerValue: null,
      repayRule: 'REPAY_BOTH',
      settleByPrinciple: 'SETTLE_BY_PRINCIPLE',
      ratioModel: 'FIXED_RATIO',
      skuConfigVos: []
    },
    {
      chargeId: 1002,
      chargeName: '管理服务费',
      direction: 'RECEIVE',
      chargeCalcChannel: 'BILLING_SYSTEM',
      calcFormula: 'PRINCIPAL_YEAR_RATE',
      receiverName: null,
      receiverCode: null,
      receiverAgentCode: null,
      receiverAgentName: null,
      repayMethod: 'ONETIME_PRINCIPAL_INTEREST',
      termRule: 'HEAD_NO_TAIL',
      free: 'NO',
      unearned: 'YES',
      chargeMethod: 'ONE_TIME_CHARGE_BEFORE',
      fallbackRule: 'ALL_INTEREST',
      fallbackUpperLimitValue: null,
      fallbackUpperLowerValue: null,
      repayRule: 'REPAY_BOTH',
      settleByPrinciple: 'SETTLE_BY_PRINCIPLE',
      ratioModel: 'FIXED_RATIO',
      skuConfigVos: []
    },
    {
      chargeId: 1004,
      chargeName: '还款保证金',
      direction: 'RECEIVE',
      chargeCalcChannel: 'BILLING_SYSTEM',
      calcFormula: 'PRINCIPAL_YEAR_RATE',
      receiverName: null,
      receiverCode: null,
      receiverAgentCode: null,
      receiverAgentName: null,
      repayMethod: 'ONETIME_PRINCIPAL_INTEREST',
      termRule: 'HEAD_NO_TAIL',
      free: 'NO',
      unearned: 'YES',
      chargeMethod: 'ONE_TIME_CHARGE_BEFORE',
      fallbackRule: 'ALL_INTEREST',
      fallbackUpperLimitValue: null,
      fallbackUpperLowerValue: null,
      repayRule: 'REPAY_BOTH',
      settleByPrinciple: null,
      ratioModel: 'FIXED_RATIO',
      skuConfigVos: []
    },
    {
      chargeId: 1023,
      chargeName: '宽限期逾期罚息',
      direction: 'RECEIVE',
      chargeCalcChannel: 'BILLING_SYSTEM',
      calcFormula: 'PRINCIPAL_YEAR_RATE',
      receiverName: null,
      receiverCode: null,
      receiverAgentCode: null,
      receiverAgentName: null,
      repayMethod: 'ONETIME_PRINCIPAL_INTEREST',
      termRule: 'HEAD_NO_TAIL',
      free: 'NO',
      unearned: 'NO',
      chargeMethod: 'ONE_TIME_CHARGE_BEFORE',
      fallbackRule: 'ALL_INTEREST',
      fallbackUpperLimitValue: null,
      fallbackUpperLowerValue: null,
      repayRule: 'REPAY_BOTH',
      settleByPrinciple: null,
      ratioModel: 'FIXED_RATIO',
      skuConfigVos: []
    }
  ];
}
